# action.yml
name: 'Hello World'
description: 'Archi CI'
inputs:
  archi-args:  # id of input
    description: 'Archi input argumentes'
    required: true
    default: ''
outputs:
  time: # id of output
    description: 'The time archi run'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
